import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';import'./refinements.css';import'./workbench.css';
const demos=[['Cutting Supervisor','supervisor@apparelflow.demo'],['Cutting Verifier','verifier@apparelflow.demo'],['Sewing Supervisor','sewing@apparelflow.demo']];
const Icon=({name,size=18})=>{const paths={hanger:<><path d="M9.2 7.2a2.8 2.8 0 1 1 3.7-2.65c0 1.85-1.9 2.1-1.9 3.45"/><path d="m3 16 8-6 8 6a1.2 1.2 0 0 1-.72 2.2H3.72A1.2 1.2 0 0 1 3 16Z"/></>,user:<><circle cx="12" cy="8" r="3.25"/><path d="M5.5 19c.7-3.2 3-5 6.5-5s5.8 1.8 6.5 5"/></>,switch:<><path d="M7 7h11l-2.5-2.5"/><path d="m18 7-2.5 2.5"/><path d="M17 17H6l2.5 2.5"/><path d="m6 17 2.5-2.5"/></>,logout:<><path d="M10 5H5v14h5"/><path d="M13 8l4 4-4 4"/><path d="M8 12h9"/></>};return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>};
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers}});const body=r.status===204?null:await r.json();if(!r.ok)throw new Error(body?.error||'Request failed');return body;}
const fmt=s=>s?.replaceAll('_',' ');
function App(){
 const[user,setUser]=useState(null),[error,setError]=useState(''),[credentials,setCredentials]=useState({email:'',password:''});
 useEffect(()=>{api('/api/me').then(x=>setUser(x.user)).catch(()=>{})},[]);
 async function login(email=credentials.email,password=credentials.password){try{setError('');const x=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});setUser(x.user)}catch(e){setError(e.message)}}
 if(!user)return <main className="authPage"><section className="authBrand"><div className="authLogo"><Icon name="hanger" size={24}/></div><div><b>ApparelFlow</b><span>Cutting Operations & Verification</span></div></section><section className="authPanel"><div className="signIn"><p className="moduleLabel">SECURE ACCESS</p><h1>Sign in</h1><p>Use your assigned factory account.</p><form onSubmit={e=>{e.preventDefault();login()}}><label>Email address<input type="email" required autoComplete="username" value={credentials.email} onChange={e=>setCredentials({...credentials,email:e.target.value})} placeholder="name@apparelflow.demo"/></label><label>Password<input type="password" required autoComplete="current-password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/></label>{error&&<div className="formError" role="alert">{error}</div>}<button className="primary authSubmit">Sign in</button></form></div><div className="demoPanel"><div><h2>Demo accounts</h2><p>Select an account to fill the sign-in form.</p></div>{demos.map(([label,email])=><button type="button" className="demoAccount" key={email} onClick={()=>{setCredentials({email,password:'Demo123!'});setError('')}}><span><b>{label}</b><small>{email}</small></span><strong>Use account</strong></button>)}<p className="demoPassword">Password: <code>Demo123!</code></p></div></section></main>;
 return <Shell user={user} switchRole={email=>login(email,'Demo123!')} logout={async()=>{await api('/api/auth/logout',{method:'POST'});setUser(null);setCredentials({email:'',password:''})}}/>
}
const roleCopy={cutting_supervisor:{title:'Cutting Orders',intro:'Create cutting orders and track their verification status.'},cutting_verifier:{title:'Verification Terminal',intro:'Record component counts and approve or reject pending batches.'},sewing_supervisor:{title:'Sewing Queue',intro:'Review verified batches before starting sewing assembly.'}};
function Shell({user,switchRole,logout}){const copy=roleCopy[user.role];return <div className="app"><nav className="topBar" aria-label="Application header"><div className="topBarInner"><div className="brand"><span className="brandMark"><Icon name="hanger" size={25}/></span><b>ApparelFlow<small>Cutting Gatekeeper</small></b></div><div className="profile"><span className="userIcon"><Icon name="user"/></span><div><b>{user.fullName}</b><small>{fmt(user.role)}</small></div><button title="Sign out" aria-label="Sign out" onClick={logout}><Icon name="logout"/><span>Sign out</span></button></div></div></nav><main className="content"><header><div><h1>{copy.title}</h1><p className="subhead">{copy.intro}</p></div><label className="roleSwitch"><span><Icon name="switch"/>Demo role</span><select aria-label="Switch demo role" value={user.email} onChange={e=>switchRole(e.target.value)}>{demos.map(([l,e])=><option key={e} value={e}>{l}</option>)}</select></label></header><Workspace user={user}/></main></div>}
function Workspace({user}){const[orders,setOrders]=useState([]),[recipes,setRecipes]=useState([]),[selected,setSelected]=useState(null),[notice,setNotice]=useState('');const load=()=>Promise.all([api('/api/orders'),api('/api/recipes')]).then(([o,r])=>{setOrders(o);setRecipes(r)});useEffect(()=>{load()},[user]);async function open(id){setSelected(await api(`/api/orders/${id}`))}const waiting=orders.filter(o=>o.status==='PENDING_VERIFICATION').length;const released=orders.filter(o=>['VERIFIED','SEWING'].includes(o.status)).length;const tableTitle=user.role==='cutting_verifier'?'Pending Verification':user.role==='sewing_supervisor'?'Verified Batches':'Order History';return <>{notice&&<div className="notice">{notice}</div>}<div className="summaryLine"><span><b>{orders.length}</b> Total</span>{user.role!=='sewing_supervisor'&&<span><b>{waiting}</b> Pending</span>}<span><b>{released}</b> Verified / Sewing</span></div>{user.role==='cutting_supervisor'&&<Create recipes={recipes} done={m=>{setNotice(m);load()}}/>}<section className="panel queue"><div className="panelHead"><h2>{tableTitle}</h2><span>{orders.length} {orders.length===1?'batch':'batches'}</span></div><div className="tableWrap"><table><thead><tr><th>Batch</th><th>Recipe</th><th>Target Qty</th><th>Fabric Roll ID</th><th>Status</th><th></th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.order_no}</b><small>{new Date(o.created_at+'Z').toLocaleString()}</small></td><td>{o.recipe_name}<small>{o.recipe_code}</small></td><td>{o.target_qty}</td><td>{o.fabric_roll_id}</td><td><Status value={o.status}/></td><td><button className="textBtn" onClick={()=>open(o.id)}>{user.role==='cutting_verifier'&&o.status==='PENDING_VERIFICATION'?'Verify':user.role==='sewing_supervisor'&&o.status==='VERIFIED'?'Review':'Details'}</button></td></tr>)}{!orders.length&&<tr><td colSpan="6" className="empty"><b>No batches found</b></td></tr>}</tbody></table></div></section>{selected&&<Detail order={selected} user={user} close={()=>setSelected(null)} changed={async m=>{setNotice(m);setSelected(null);await load()}}/>}</>}
const Stat=({n,label})=><div className="stat"><strong>{n}</strong><span>{label}</span></div>;
const Status=({value})=><span className={'badge '+value.toLowerCase()}>{fmt(value)}</span>;
function Create({recipes,done}){
 const blank={recipeId:'',targetQty:'',fabricRollId:'',actualFabricYds:''};
 const[form,setForm]=useState(blank),[error,setError]=useState('');
 const recipe=recipes.find(r=>r.id===Number(form.recipeId));
 const expected=recipe?recipe.std_fabric_yards*Number(form.targetQty||0):0;
 const actual=Number(form.actualFabricYds||0);
 const variance=expected?((actual-expected)/expected)*100:null;
 const ready=Boolean(recipe&&Number(form.targetQty)>0&&form.fabricRollId.trim()&&actual>0);
 const update=(field,value)=>{setForm(current=>({...current,[field]:value}));setError('')};
 async function submit(e){e.preventDefault();try{const created=await api('/api/orders',{method:'POST',body:JSON.stringify({recipeId:Number(form.recipeId),targetQty:Number(form.targetQty),fabricRollId:form.fabricRollId.trim(),actualFabricYds:actual})});await api(`/api/orders/${created.order.id}/submit`,{method:'POST'});setForm(blank);setError('');done('The batch is now waiting at the verification station.')}catch(x){setError(x.message)}}
 return <section className="panel create"><div className="createIntro"><h2>Create Cutting Order</h2><span>All fields required</span></div><div className="createBody"><form onSubmit={submit}><div className="formGrid"><label>Production Recipe<select required value={form.recipeId} onChange={e=>update('recipeId',e.target.value)}><option value="">Select recipe</option>{recipes.map(r=><option value={r.id} key={r.id}>{r.name} · {r.recipe_code}</option>)}</select></label><label>Target Batch Quantity<div className="unitInput"><input required min="1" step="1" type="number" value={form.targetQty} onChange={e=>update('targetQty',e.target.value)} placeholder="50"/><span>garments</span></div></label><label>Fabric Roll ID<input required value={form.fabricRollId} onChange={e=>update('fabricRollId',e.target.value)} placeholder="FAB-ROLL-882"/></label><label>Actual Fabric Used<div className="unitInput"><input required min="0.01" step="0.01" type="number" value={form.actualFabricYds} onChange={e=>update('actualFabricYds',e.target.value)} placeholder="90"/><span>yards</span></div></label></div>{error&&<div className="formError" role="alert"><b>Unable to create order</b><span>{error}</span></div>}<div className="formFooter"><span/><button className="primary" disabled={!ready}>Submit for Verification</button></div></form><aside className="handoffAside"><h3>Calculated Requirements</h3><p className="asideHint">{recipe?`${recipe.name} · ${form.targetQty||0} garments`:'Select a production recipe.'}</p><dl><div><dt>Component Types</dt><dd>{recipe?recipe.components.length:'—'}</dd></div><div><dt>Expected Fabric</dt><dd>{recipe&&form.targetQty?`${expected.toFixed(1)} yd`:'—'}</dd></div><div><dt>Fabric Wastage</dt><dd className={variance!==null&&variance>recipe?.wastage_cap?'over':''}>{variance!==null&&actual?`${variance>0?'+':''}${variance.toFixed(1)}%`:'—'}</dd></div><div><dt>Wastage Cap</dt><dd>{recipe?`${recipe.wastage_cap}%`:'—'}</dd></div></dl>{recipe&&<div className="componentPreview"><small>EXPECTED COMPONENTS</small>{recipe.components.map(c=><span key={c.id}>{c.component_name}<b>{form.targetQty?c.pieces_per_garment*Number(form.targetQty):c.pieces_per_garment}</b></span>)}</div>}</aside></div></section>}
function Detail({order,user,close,changed}){
 const[counts,setCounts]=useState(Object.fromEntries(order.items.map(i=>[i.component_id,i.actual_qty??'']))),[reason,setReason]=useState(''),[error,setError]=useState('');
 const calc=i=>counts[i.component_id]===''?null:Number(counts[i.component_id])===i.expected_qty?'GREEN':Number(counts[i.component_id])>i.expected_qty?'YELLOW':'RED';
 const complete=order.items.every(i=>counts[i.component_id]!==''),hasRed=order.items.some(i=>calc(i)==='RED');
 const countPayload=()=>({items:order.items.map(i=>({componentId:i.component_id,actualQty:Number(counts[i.component_id])}))});
 async function persistCounts(){await api(`/api/orders/${order.id}/counts`,{method:'PUT',body:JSON.stringify(countPayload())})}
 async function decide(path,body){try{setError('');if(complete)await persistCounts();await api(`/api/orders/${order.id}/${path}`,{method:'POST',body:JSON.stringify(body||{})});changed(path==='approve'?'Batch verified and released to sewing.':'Batch rejected; the counts and reason are preserved in its audit record.')}catch(e){setError(e.message)}}
 async function start(){try{await api(`/api/sewing/${order.id}/start`,{method:'POST'});changed('Sewing assembly started.')}catch(e){setError(e.message)}}
 async function recut(){try{await api(`/api/orders/${order.id}/recut`,{method:'POST'});changed('A linked re-cut batch was created and sent to verification.')}catch(e){setError(e.message)}}
 return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="drawer"><button className="close" aria-label="Close details" onClick={close}>×</button><p className="eyebrow">{order.order_no}</p><h2>{order.recipe_name}</h2><div className="meta"><span>Order size <b>{order.target_qty} garments</b></span><span>Fabric used <b>{order.actual_fabric_yds} yds</b></span><span>Current state <Status value={order.status}/></span></div><h3>{user.role==='cutting_verifier'?'Enter the physical bundle counts':'Component handover'}</h3>{user.role==='cutting_verifier'&&order.status==='PENDING_VERIFICATION'&&<p className="drawerHelp">Use whole pieces only. Status updates as you type; any red shortage blocks release.</p>}{order.items.map(i=>{const state=calc(i)||i.status;return <div className="component" key={i.id}><div><b>{i.component_name}</b><small>Expected: {i.expected_qty} pieces</small></div>{user.role==='cutting_verifier'&&order.status==='PENDING_VERIFICATION'?<input aria-label={`${i.component_name} actual count`} min="0" step="1" type="number" value={counts[i.component_id]} onChange={e=>setCounts({...counts,[i.component_id]:e.target.value})} placeholder="Actual"/>:<strong>{i.actual_qty??'Not counted'}</strong>}{state&&<Status value={state}/>}</div>})}{user.role==='cutting_verifier'&&order.status==='PENDING_VERIFICATION'&&<div className="actions"><button className="approve" onClick={()=>decide('approve')} disabled={!complete||hasRed}>Save counts and approve</button>{hasRed&&<p className="hardstop"><b>Shortage found.</b> This batch cannot go to sewing. Add a reason and return it for re-cutting.</p>}<label>Reason for returning this batch<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Example: 3 front panels missing from bundle 2"/></label><button className="danger" onClick={()=>decide('reject',{reason})} disabled={reason.trim().length<3}>Save counts and return for re-cutting</button></div>}{user.role==='cutting_supervisor'&&order.status==='REJECTED'&&<button className="primary full" onClick={recut}>Create linked re-cut batch</button>}{user.role==='sewing_supervisor'&&order.status==='VERIFIED'&&<button className="primary full" onClick={start}>Confirm handover and start sewing</button>}{order.logs?.map(l=><div className={`audit ${l.wastage_pct>order.wastage_cap?'overCap':''}`} key={l.id}><b>{l.decision} by {l.verifier_name}</b><span>{new Date(l.timestamp+'Z').toLocaleString()} · wastage {l.wastage_pct}% {l.wastage_pct>order.wastage_cap?`(above ${order.wastage_cap}% cap)`:''}</span>{l.rejection_note&&<p>{l.rejection_note}</p>}</div>)}{error&&<p className="error">{error}</p>}</section></div>}
createRoot(document.getElementById('root')).render(<App/>);
