CREATE TABLE IF NOT EXISTS users(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN('cutting_supervisor','cutting_verifier','sewing_supervisor')),
  full_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recipes(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  std_fabric_yards NUMERIC(10,2) NOT NULL CHECK(std_fabric_yards > 0),
  wastage_cap NUMERIC(6,2) NOT NULL CHECK(wastage_cap >= 0)
);

CREATE TABLE IF NOT EXISTS recipe_components(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id BIGINT NOT NULL REFERENCES recipes(id),
  component_name TEXT NOT NULL,
  pieces_per_garment INTEGER NOT NULL CHECK(pieces_per_garment > 0),
  image_url TEXT,
  UNIQUE(recipe_id, component_name)
);

CREATE TABLE IF NOT EXISTS cutting_orders(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no TEXT UNIQUE NOT NULL,
  recipe_id BIGINT NOT NULL REFERENCES recipes(id),
  target_qty INTEGER NOT NULL CHECK(target_qty > 0),
  fabric_roll_id TEXT NOT NULL,
  actual_fabric_yds NUMERIC(12,2) NOT NULL CHECK(actual_fabric_yds > 0),
  status TEXT NOT NULL CHECK(status IN('CUTTING_IN_PROGRESS','PENDING_VERIFICATION','VERIFIED','REJECTED','SEWING')),
  created_by BIGINT NOT NULL REFERENCES users(id),
  parent_order_id BIGINT REFERENCES cutting_orders(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sewing_started_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS verification_items(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES cutting_orders(id) ON DELETE CASCADE,
  component_id BIGINT NOT NULL REFERENCES recipe_components(id),
  expected_qty INTEGER NOT NULL CHECK(expected_qty > 0),
  actual_qty INTEGER CHECK(actual_qty >= 0),
  status TEXT CHECK(status IN('GREEN','YELLOW','RED')),
  UNIQUE(order_id, component_id)
);

CREATE TABLE IF NOT EXISTS verification_logs(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES cutting_orders(id),
  verifier_id BIGINT NOT NULL REFERENCES users(id),
  decision TEXT NOT NULL CHECK(decision IN('APPROVED','REJECTED')),
  rejection_note TEXT,
  wastage_pct NUMERIC(8,2) NOT NULL,
  component_variances JSONB NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS cutting_orders_status_created_idx ON cutting_orders(status, created_at);
CREATE INDEX IF NOT EXISTS cutting_orders_parent_idx ON cutting_orders(parent_order_id);
CREATE INDEX IF NOT EXISTS verification_items_order_status_idx ON verification_items(order_id, status);
CREATE INDEX IF NOT EXISTS verification_logs_order_idx ON verification_logs(order_id, timestamp);
CREATE UNIQUE INDEX IF NOT EXISTS verification_logs_one_decision_per_order_idx ON verification_logs(order_id);

CREATE OR REPLACE FUNCTION reject_audit_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'verification logs are immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS verification_logs_no_update ON verification_logs;
CREATE TRIGGER verification_logs_no_update BEFORE UPDATE ON verification_logs
FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();

DROP TRIGGER IF EXISTS verification_logs_no_delete ON verification_logs;
CREATE TRIGGER verification_logs_no_delete BEFORE DELETE ON verification_logs
FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();

CREATE OR REPLACE FUNCTION enforce_order_transition() RETURNS trigger AS $$
BEGIN
  IF OLD.status <> NEW.status AND NOT (
    (OLD.status = 'CUTTING_IN_PROGRESS' AND NEW.status = 'PENDING_VERIFICATION') OR
    (OLD.status = 'PENDING_VERIFICATION' AND NEW.status IN ('VERIFIED','REJECTED')) OR
    (OLD.status = 'VERIFIED' AND NEW.status = 'SEWING')
  ) THEN
    RAISE EXCEPTION 'illegal cutting order state transition';
  END IF;
  IF NEW.status = 'VERIFIED' AND OLD.status <> 'VERIFIED' THEN
    IF NOT EXISTS (SELECT 1 FROM verification_items WHERE order_id = NEW.id) THEN
      RAISE EXCEPTION 'verification requires component counts';
    END IF;
    IF EXISTS (SELECT 1 FROM verification_items WHERE order_id = NEW.id AND (actual_qty IS NULL OR status IS NULL OR status = 'RED')) THEN
      RAISE EXCEPTION 'shortage or missing count blocks verification';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS cutting_orders_transition_gate ON cutting_orders;
CREATE TRIGGER cutting_orders_transition_gate BEFORE UPDATE OF status ON cutting_orders
FOR EACH ROW EXECUTE FUNCTION enforce_order_transition();

CREATE OR REPLACE FUNCTION freeze_verification_items() RETURNS trigger AS $$
BEGIN
  IF (SELECT status FROM cutting_orders WHERE id = OLD.order_id) <> 'PENDING_VERIFICATION' THEN
    RAISE EXCEPTION 'verification counts are immutable after decision';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS verification_items_freeze_after_decision ON verification_items;
CREATE TRIGGER verification_items_freeze_after_decision BEFORE UPDATE ON verification_items
FOR EACH ROW EXECUTE FUNCTION freeze_verification_items();
