import express from 'express';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import bcrypt from 'bcryptjs';
import { sign,requireAuth,requireRole } from './middleware/auth.js';
import { createOrderSchema,countsSchema,rejectSchema,detailedOrder,items,logDecision } from './services/orders.js';
import { componentStatus,requirePending,requireApprovable } from './domain/gatekeeper.js';

const route = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next);

export function createApp(db){
 const app=express();
 app.use(helmet({contentSecurityPolicy:false}));
 app.use(express.json({limit:'50kb'}));
 app.use(cookieParser());

 app.post('/api/auth/login',route(async(req,res)=>{const {email,password}=req.body||{};const user=await db.one('SELECT * FROM users WHERE email=$1',[String(email||'').toLowerCase()]);if(!user||!await bcrypt.compare(String(password||''),user.password_hash))return res.status(401).json({error:'Invalid credentials'});res.cookie('session',sign(user),{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',maxAge:28800000});res.json({user:{id:user.id,email:user.email,role:user.role,fullName:user.full_name}});}));
 app.post('/api/auth/logout',(_req,res)=>{res.clearCookie('session');res.status(204).end();});
 app.get('/api/me',requireAuth,route(async(req,res)=>{const u=await db.one('SELECT id,email,role,full_name AS "fullName" FROM users WHERE id=$1',[req.user.sub]);res.json({user:u});}));
 app.get('/api/recipes',requireAuth,route(async(_req,res)=>{const rows=await db.many('SELECT * FROM recipes ORDER BY name');res.json(await Promise.all(rows.map(async r=>({...r,components:await db.many('SELECT * FROM recipe_components WHERE recipe_id=$1 ORDER BY id',[r.id])}))));}));

 app.post('/api/orders',requireAuth,requireRole('cutting_supervisor'),route(async(req,res)=>{const p=createOrderSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid order',details:p.error.flatten()});const recipe=await db.one('SELECT id FROM recipes WHERE id=$1',[p.data.recipeId]);if(!recipe)return res.status(404).json({error:'Recipe not found'});const id=await db.transaction(async tx=>{const no=`CUT-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const out=await tx.one(`INSERT INTO cutting_orders(order_no,recipe_id,target_qty,fabric_roll_id,actual_fabric_yds,status,created_by) VALUES($1,$2,$3,$4,$5,'CUTTING_IN_PROGRESS',$6) RETURNING id`,[no,p.data.recipeId,p.data.targetQty,p.data.fabricRollId,p.data.actualFabricYds,req.user.sub]);const comps=await tx.many('SELECT * FROM recipe_components WHERE recipe_id=$1',[p.data.recipeId]);for(const c of comps)await tx.query('INSERT INTO verification_items(order_id,component_id,expected_qty) VALUES($1,$2,$3)',[out.id,c.id,c.pieces_per_garment*p.data.targetQty]);return out.id;});res.status(201).json({order:await detailedOrder(db,id)});}));
 app.post('/api/orders/:id/submit',requireAuth,requireRole('cutting_supervisor'),route(async(req,res)=>{const out=await db.query(`UPDATE cutting_orders SET status='PENDING_VERIFICATION',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND created_by=$2 AND status='CUTTING_IN_PROGRESS'`,[req.params.id,req.user.sub]);if(!out.rowCount)return res.status(409).json({error:'Only your in-progress cutting order can be submitted'});res.json({order:await detailedOrder(db,req.params.id)});}));
 app.post('/api/orders/:id/recut',requireAuth,requireRole('cutting_supervisor'),route(async(req,res)=>{try{const id=await db.transaction(async tx=>{const source=await detailedOrder(tx,req.params.id);if(!source||source.status!=='REJECTED')throw Object.assign(new Error('Only a rejected order can be re-cut'),{status:409});const no=`RECUT-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const out=await tx.one(`INSERT INTO cutting_orders(order_no,recipe_id,target_qty,fabric_roll_id,actual_fabric_yds,status,created_by,parent_order_id) VALUES($1,$2,$3,$4,$5,'CUTTING_IN_PROGRESS',$6,$7) RETURNING id`,[no,source.recipe_id,source.target_qty,source.fabric_roll_id,source.actual_fabric_yds,req.user.sub,source.id]);for(const item of await items(tx,source.id))await tx.query('INSERT INTO verification_items(order_id,component_id,expected_qty) VALUES($1,$2,$3)',[out.id,item.component_id,item.expected_qty]);await tx.query(`UPDATE cutting_orders SET status='PENDING_VERIFICATION',updated_at=CURRENT_TIMESTAMP WHERE id=$1`,[out.id]);return out.id;});res.status(201).json({order:await detailedOrder(db,id)});}catch(e){res.status(e.status||500).json({error:e.message});}}));

 app.get('/api/orders',requireAuth,route(async(req,res)=>{let sql=`SELECT o.*,r.name recipe_name,r.recipe_code,u.full_name creator_name FROM cutting_orders o JOIN recipes r ON r.id=o.recipe_id JOIN users u ON u.id=o.created_by`;if(req.user.role==='sewing_supervisor')sql+=` WHERE o.status IN ('VERIFIED','SEWING')`;else if(req.user.role==='cutting_verifier')sql+=` WHERE o.status<>'CUTTING_IN_PROGRESS'`;sql+=' ORDER BY o.created_at DESC';res.json(await db.many(sql));}));
 app.get('/api/orders/:id',requireAuth,route(async(req,res)=>{const o=await detailedOrder(db,req.params.id);if(!o)return res.status(404).json({error:'Order not found'});if(req.user.role==='sewing_supervisor'&&!['VERIFIED','SEWING'].includes(o.status))return res.status(404).json({error:'Order not found'});res.json({...o,items:await items(db,o.id),logs:await db.many(`SELECT l.*,u.full_name verifier_name FROM verification_logs l JOIN users u ON u.id=l.verifier_id WHERE order_id=$1 ORDER BY timestamp`,[o.id])});}));
 app.put('/api/orders/:id/counts',requireAuth,requireRole('cutting_verifier'),route(async(req,res)=>{const p=countsSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Counts must be non-negative whole numbers'});const o=await detailedOrder(db,req.params.id);if(!o||o.status!=='PENDING_VERIFICATION')return res.status(409).json({error:'Order is not pending verification'});const current=await items(db,o.id);if(p.data.items.length!==current.length||new Set(p.data.items.map(x=>x.componentId)).size!==current.length||p.data.items.some(x=>!current.some(c=>Number(c.component_id)===x.componentId)))return res.status(422).json({error:'Every recipe component must be counted exactly once'});await db.transaction(async tx=>{for(const x of p.data.items){const expected=current.find(c=>Number(c.component_id)===x.componentId).expected_qty;await tx.query(`UPDATE verification_items SET actual_qty=$1,status=$2 WHERE order_id=$3 AND component_id=$4`,[x.actualQty,componentStatus(x.actualQty,expected),o.id,x.componentId]);}});res.json({items:await items(db,o.id)});}));
 app.post('/api/orders/:id/approve',requireAuth,requireRole('cutting_verifier'),route(async(req,res)=>{try{await db.transaction(async tx=>{const o=await detailedOrder(tx,req.params.id);requirePending(o);requireApprovable(await items(tx,o.id));await tx.query(`UPDATE cutting_orders SET status='VERIFIED',updated_at=CURRENT_TIMESTAMP WHERE id=$1`,[o.id]);await logDecision(tx,o,req.user.sub,'APPROVED');});res.json({order:await detailedOrder(db,req.params.id)});}catch(e){res.status(e.status||500).json({error:e.message,code:e.code});}}));
 app.post('/api/orders/:id/reject',requireAuth,requireRole('cutting_verifier'),route(async(req,res)=>{const p=rejectSchema.safeParse(req.body);if(!p.success)return res.status(422).json({error:'A reason of at least 3 characters is required'});try{await db.transaction(async tx=>{const o=await detailedOrder(tx,req.params.id);requirePending(o);await tx.query(`UPDATE cutting_orders SET status='REJECTED',updated_at=CURRENT_TIMESTAMP WHERE id=$1`,[o.id]);await logDecision(tx,o,req.user.sub,'REJECTED',p.data.reason);});res.json({order:await detailedOrder(db,req.params.id)});}catch(e){res.status(e.status||500).json({error:e.message,code:e.code});}}));
 app.get('/api/sewing/queue',requireAuth,requireRole('sewing_supervisor'),route(async(_req,res)=>res.json(await db.many(`SELECT o.*,r.name recipe_name,r.recipe_code,r.wastage_cap,l.wastage_pct,l.timestamp verified_at,u.full_name verifier_name FROM cutting_orders o JOIN recipes r ON r.id=o.recipe_id JOIN verification_logs l ON l.order_id=o.id AND l.decision='APPROVED' JOIN users u ON u.id=l.verifier_id WHERE o.status='VERIFIED' ORDER BY l.timestamp`))));
 app.post('/api/sewing/:id/start',requireAuth,requireRole('sewing_supervisor'),route(async(req,res)=>{const out=await db.query(`UPDATE cutting_orders SET status='SEWING',sewing_started_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND status='VERIFIED'`,[req.params.id]);if(!out.rowCount)return res.status(409).json({error:'Only verified orders can start sewing'});res.json({order:await detailedOrder(db,req.params.id)});}));
 app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Internal server error'});});
 return app;
}
